from __future__ import annotations

from pathlib import Path
from typing import Any

from .constraints import format_value, load_constraints


def build_livelink_script(constraints_path: str | Path) -> str:
    cfg = load_constraints(constraints_path)
    return build_livelink_script_from_constraints(cfg)


def build_livelink_script_from_constraints(cfg: dict[str, Any]) -> str:
    if cfg["geometry"].get("type") == "interval_1d":
        return _build_one_dimensional_script(cfg)
    if cfg["physics"] == "solid_mechanics_2d":
        return _build_two_dimensional_structural_script(cfg)
    if cfg["physics"] == "thermal_stress_2d":
        return _build_two_dimensional_thermal_stress_script(cfg)

    model_name = cfg["model_name"]
    geometry = cfg["geometry"]["parameters"]
    materials = cfg["materials"]
    bc = cfg["boundary_conditions"]
    mesh = cfg["mesh"]
    outputs = cfg["outputs"]

    output_lines = []
    for tag, expr in outputs.items():
        output_lines.extend(
            [
                f"model.result.numerical.create('{tag}', 'EvalGlobal');",
                f"model.result.numerical('{tag}').set('expr', '{expr}');",
            ]
        )

    sweep_lines = []
    for name, values in cfg.get("sweep", {}).items():
        joined = " ".join(str(v) for v in values)
        sweep_lines.append(f"% Sweep candidate {name}: [{joined}]")

    return "\n".join(
        [
            f"function model = generated_build_{model_name}()",
            f"%GENERATED_BUILD_{model_name.upper()} Build a constrained COMSOL starter model.",
            "% Generated by comsol_training_small_model.",
            "%",
            "% Run inside COMSOL with MATLAB:",
            f"%   model = generated_build_{model_name};",
            "",
            "import com.comsol.model.*",
            "import com.comsol.model.util.*",
            "",
            "model = ModelUtil.create('Model');",
            f"model.label('{model_name}.mph');",
            "",
            _param_line("L", geometry["L"], "Rectangle length"),
            _param_line("W", geometry["W"], "Rectangle width"),
            _param_line("k", materials["k"], "Thermal conductivity"),
            _param_line("rho", materials["rho"], "Density"),
            _param_line("Cp", materials["Cp"], "Heat capacity"),
            _param_line("heat_flux", bc["heat_flux"], "Boundary heat flux"),
            _param_line("hconv", bc["h"], "Convective heat transfer coefficient"),
            _param_line("Text", bc["Text"], "External temperature"),
            _param_line("hmax", mesh["hmax"], "Maximum mesh size"),
            "",
            *sweep_lines,
            "",
            "model.component.create('comp1', true);",
            "model.component('comp1').geom.create('geom1', 2);",
            "model.component('comp1').geom('geom1').lengthUnit('m');",
            "model.component('comp1').geom('geom1').create('r1', 'Rectangle');",
            "model.component('comp1').geom('geom1').feature('r1').set('size', {'L' 'W'});",
            "model.component('comp1').geom('geom1').run;",
            "",
            "model.component('comp1').material.create('mat1', 'Common');",
            "model.component('comp1').material('mat1').label('Constrained solid');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', 'k');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp');",
            "",
            "model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');",
            "% Boundary selections are placeholders. Inspect geometry boundary numbers before production runs.",
            "model.component('comp1').physics('ht').create('hf1', 'HeatFluxBoundary', 1);",
            "model.component('comp1').physics('ht').feature('hf1').selection.set([1]);",
            "model.component('comp1').physics('ht').feature('hf1').set('q0', 'heat_flux');",
            "model.component('comp1').physics('ht').create('hf2', 'HeatFluxBoundary', 1);",
            "model.component('comp1').physics('ht').feature('hf2').selection.set([2 3 4]);",
            "model.component('comp1').physics('ht').feature('hf2').set('HeatFluxType', 'ConvectiveHeatFlux');",
            "model.component('comp1').physics('ht').feature('hf2').set('h', 'hconv');",
            "model.component('comp1').physics('ht').feature('hf2').set('Text', 'Text');",
            "",
            "model.component('comp1').mesh.create('mesh1');",
            "model.component('comp1').mesh('mesh1').create('size1', 'Size');",
            "model.component('comp1').mesh('mesh1').feature('size1').set('custom', true);",
            "model.component('comp1').mesh('mesh1').feature('size1').set('hmax', 'hmax');",
            "model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');",
            "model.component('comp1').mesh('mesh1').run;",
            "",
            "model.component('comp1').cpl.create('maxop1', 'Maximum');",
            "model.component('comp1').cpl('maxop1').selection.all;",
            "model.component('comp1').cpl.create('aveop1', 'Average');",
            "model.component('comp1').cpl('aveop1').selection.all;",
            "",
            "model.study.create('std1');",
            "model.study('std1').create('stat', 'Stationary');",
            "model.study('std1').createAutoSequences('all');",
            "model.study('std1').run;",
            "",
            *output_lines,
            "",
            "% Saving is handled by the execution wrapper with mphsave(model, output_path).",
            "end",
            "",
        ]
    )


def write_livelink_script(constraints_path: str | Path, output_path: str | Path) -> Path:
    destination = Path(output_path)
    destination.write_text(build_livelink_script(constraints_path), encoding="utf-8")
    return destination


def _param_line(name: str, spec: dict[str, Any], description: str) -> str:
    return f"model.param.set('{name}', '{format_value(spec)}', '{description}');"


def _build_one_dimensional_script(cfg: dict[str, Any]) -> str:
    """Build a small, reviewable 1D benchmark script from a common JSON schema."""
    model_name = cfg["model_name"]
    geometry = cfg["geometry"]["parameters"]
    study_type = cfg["study"]["type"]
    physics = cfg["physics"]
    output_lines = []
    for tag, expr in cfg["outputs"].items():
        output_lines.extend([
            f"model.result.numerical.create('{tag}', 'EvalGlobal');",
            f"model.result.numerical('{tag}').set('expr', '{expr}');",
        ])

    parameter_lines = [_param_line("L", geometry["L"], "One-dimensional domain length")]
    for section in ("materials", "boundary_conditions", "mesh"):
        for name, spec in cfg[section].items():
            parameter_lines.append(_param_line(name, spec, name.replace("_", " ")))
    for name, spec in cfg.get("sources", {}).items():
        parameter_lines.append(_param_line(name, spec, name.replace("_", " ")))

    physics_lines = _one_dimensional_physics_lines(physics)
    study_lines = ["model.study('std1').create('stat', 'Stationary');"]
    if study_type == "transient":
        time_range = cfg["study"].get("time_range", "range(0,1,10)")
        study_lines = [
            "model.study('std1').create('time', 'Transient');",
            f"model.study('std1').feature('time').set('tlist', '{time_range}');",
        ]
    if study_type == "eigenfrequency":
        study_lines = [
            "model.study('std1').create('eig', 'Eigenfrequency');",
            f"model.study('std1').feature('eig').set('neigs', {int(cfg['study'].get('neigs', 3))});",
            f"model.study('std1').feature('eig').set('shift', '{cfg['study'].get('shift', 'f1_ref')}');",
        ]
    study_feature = {"transient": "time", "eigenfrequency": "eig"}.get(study_type, "stat")
    activation_lines = _one_dimensional_study_activation_lines(physics, study_feature)

    return "\n".join([
        f"function model = generated_build_{model_name}()",
        f"%GENERATED_BUILD_{model_name.upper()} 1D COMSOL benchmark model.",
        "% Boundary 1 is x=0 and boundary 2 is x=L for an interval geometry. Verify after build.",
        "import com.comsol.model.*",
        "import com.comsol.model.util.*",
        "",
        "model = ModelUtil.create('Model');",
        f"model.label('{model_name}.mph');",
        *parameter_lines,
        "",
        "model.component.create('comp1', true);",
        "model.component('comp1').geom.create('geom1', 1);",
        "model.component('comp1').geom('geom1').lengthUnit('m');",
        "model.component('comp1').geom('geom1').create('i1', 'Interval');",
        "model.component('comp1').geom('geom1').feature('i1').set('p1', '0');",
        "model.component('comp1').geom('geom1').feature('i1').set('p2', 'L');",
        "model.component('comp1').geom('geom1').run;",
        "",
        *physics_lines,
        "",
        "model.component('comp1').mesh.create('mesh1');",
        "model.component('comp1').mesh('mesh1').create('size1', 'Size');",
        "model.component('comp1').mesh('mesh1').feature('size1').set('custom', true);",
        "model.component('comp1').mesh('mesh1').feature('size1').set('hmax', 'hmax');",
        "model.component('comp1').mesh('mesh1').create('edg1', 'Edge');",
        "model.component('comp1').mesh('mesh1').run;",
        "",
        "model.component('comp1').cpl.create('maxop1', 'Maximum');",
        "model.component('comp1').cpl('maxop1').selection.all;",
        "model.study.create('std1');",
        *study_lines,
        *activation_lines,
        "model.study('std1').createAutoSequences('all');",
        "model.study('std1').run;",
        *output_lines,
        "% Saving is handled by the execution wrapper with mphsave(model, output_path).",
        "end",
        "",
    ])


def _one_dimensional_study_activation_lines(physics: str, study_feature: str) -> list[str]:
    interfaces = {
        "heat_transfer_1d": ["ht"],
        "diffusion_1d": ["tds"],
        "electrothermal_1d": ["ec", "ht"],
        "axial_bar_1d": ["solid"],
        "acoustic_pressure_1d": ["acpr"],
    }.get(physics, ["ht"])
    return [f"model.study('std1').feature('{study_feature}').activate('{tag}', true);" for tag in interfaces]


def _one_dimensional_physics_lines(physics: str) -> list[str]:
    material = [
        "model.component('comp1').material.create('mat1', 'Common');",
        "model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', 'k');",
        "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho');",
        "model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp');",
    ]
    if physics == "heat_transfer_1d":
        return material + [
            "model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');",
            "model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 0);",
            "model.component('comp1').physics('ht').feature('temp1').selection.set([1]);",
            "model.component('comp1').physics('ht').feature('temp1').set('T0', 'T_left');",
            "model.component('comp1').physics('ht').create('temp2', 'TemperatureBoundary', 0);",
            "model.component('comp1').physics('ht').feature('temp2').selection.set([2]);",
            "model.component('comp1').physics('ht').feature('temp2').set('T0', 'T_right');",
        ]
    if physics == "diffusion_1d":
        return [
            "model.component('comp1').physics.create('tds', 'DilutedSpecies', 'geom1');",
            "model.component('comp1').physics('tds').selection.all;",
            "model.component('comp1').physics('tds').feature('sp1').set('f', '1');",
            "model.component('comp1').physics('tds').feature('sp1').set('z', '0');",
            "model.component('comp1').physics('tds').feature('cdm1').set('D_c', {'D'});",
            "model.component('comp1').physics('tds').feature('init1').set('initc', 'c_right');",
            "model.component('comp1').physics('tds').create('conc1', 'Concentration', 0);",
            "model.component('comp1').physics('tds').feature('conc1').selection.set([1]);",
            "model.component('comp1').physics('tds').feature('conc1').set('c0', {'c_left'});",
            "model.component('comp1').physics('tds').feature('conc1').set('species', '1');",
            "model.component('comp1').physics('tds').create('conc2', 'Concentration', 0);",
            "model.component('comp1').physics('tds').feature('conc2').selection.set([2]);",
            "model.component('comp1').physics('tds').feature('conc2').set('c0', {'c_right'});",
            "model.component('comp1').physics('tds').feature('conc2').set('species', '1');",
        ]
    if physics == "acoustic_pressure_1d":
        return [
            "model.component('comp1').material.create('mat1', 'Common');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', 'c');",
            "model.component('comp1').physics.create('acpr', 'PressureAcoustics', 'geom1');",
            "% Pressure-release ends model an open-open acoustic tube. Verify boundary numbering after build.",
            "model.component('comp1').physics('acpr').create('p1', 'Pressure', 0);",
            "model.component('comp1').physics('acpr').feature('p1').selection.set([1 2]);",
            "model.component('comp1').physics('acpr').feature('p1').set('p0', 'p_release');",
        ]
    if physics == "axial_bar_1d":
        return [
            "model.component('comp1').material.create('mat1', 'Common');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho_mat');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', 'E_mod');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', 'nu_mat');",
            "% Use the base Solid Mechanics interface so this axial-bar template does not require the Beam module.",
            "model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');",
            "model.component('comp1').physics('solid').selection.all;",
            "model.component('comp1').physics('solid').create('fix1', 'Fixed', 0);",
            "model.component('comp1').physics('solid').feature('fix1').selection.set([1]);",
            "model.component('comp1').physics('solid').create('bndl1', 'BoundaryLoad', 0);",
            "model.component('comp1').physics('solid').feature('bndl1').selection.set([2]);",
            "model.component('comp1').physics('solid').feature('bndl1').set('FperArea', {'p_load' '0' '0'});",
        ]
    if physics == "electrothermal_1d":
        return material + [
            "model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', 'sigma');",
            "model.component('comp1').physics.create('ec', 'ConductiveMedia', 'geom1');",
            "model.component('comp1').physics('ec').selection.all;",
            "model.component('comp1').physics('ec').create('pot1', 'ElectricPotential', 0);",
            "model.component('comp1').physics('ec').feature('pot1').selection.set([1]);",
            "model.component('comp1').physics('ec').feature('pot1').set('V0', 'V_left');",
            "model.component('comp1').physics('ec').create('gnd1', 'Ground', 0);",
            "model.component('comp1').physics('ec').feature('gnd1').selection.set([2]);",
            "model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');",
            "model.component('comp1').physics('ht').selection.all;",
            "model.component('comp1').physics('ht').create('hs1', 'HeatSource', 1);",
            "model.component('comp1').physics('ht').feature('hs1').selection.all;",
            "model.component('comp1').physics('ht').feature('hs1').set('Q0', 'ec.Qh');",
            "model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 0);",
            "model.component('comp1').physics('ht').feature('temp1').selection.set([1]);",
            "model.component('comp1').physics('ht').feature('temp1').set('T0', 'T_left');",
            "model.component('comp1').physics('ht').create('temp2', 'TemperatureBoundary', 0);",
            "model.component('comp1').physics('ht').feature('temp2').selection.set([2]);",
            "model.component('comp1').physics('ht').feature('temp2').set('T0', 'T_right');",
        ]
    return material + [
        "model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');",
        "model.component('comp1').physics.create('beam', 'Beam', 'geom1');",
        "% Configure Thermal Expansion manually after verifying the Beam cross section and reference temperature.",
    ]


def _build_two_dimensional_structural_script(cfg: dict[str, Any]) -> str:
    g, m, bc, mesh = cfg["geometry"]["parameters"], cfg["materials"], cfg["boundary_conditions"], cfg["mesh"]
    p = lambda name, spec: _param_line(name, spec, name)
    output_lines = [f"model.result.numerical.create('{tag}', 'EvalGlobal'); model.result.numerical('{tag}').set('expr', '{expr}');" for tag, expr in cfg["outputs"].items()]
    return "\n".join([
        f"function model = generated_build_{cfg['model_name']}()",
        "import com.comsol.model.*", "import com.comsol.model.util.*", "model = ModelUtil.create('Model');",
        p("L", g["L"]), p("W", g["W"]), p("E_mod", m["E"]), p("nu_mat", m["nu"]), p("rho_mat", m["rho"]), p("p_load", bc["p_load"]), p("hmax", mesh["hmax"]),
        "model.component.create('comp1', true);", "model.component('comp1').geom.create('geom1', 2);", "model.component('comp1').geom('geom1').create('r1', 'Rectangle');", "model.component('comp1').geom('geom1').feature('r1').set('size', {'L' 'W'});", "model.component('comp1').geom('geom1').run;",
        "model.component('comp1').material.create('mat1', 'Common');", "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho_mat');", "model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', 'E_mod');", "model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', 'nu_mat');",
        "model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');", "model.component('comp1').physics('solid').selection.all;", "model.component('comp1').physics('solid').create('fix1', 'Fixed', 1);", "model.component('comp1').physics('solid').feature('fix1').selection.set([1]);", "model.component('comp1').physics('solid').create('bndl1', 'BoundaryLoad', 1);", "model.component('comp1').physics('solid').feature('bndl1').selection.set([3]);", "model.component('comp1').physics('solid').feature('bndl1').set('FperArea', {'p_load' '0' '0'});",
        "model.component('comp1').mesh.create('mesh1');", "model.component('comp1').mesh('mesh1').create('size1', 'Size');", "model.component('comp1').mesh('mesh1').feature('size1').set('custom', true);", "model.component('comp1').mesh('mesh1').feature('size1').set('hmax', 'hmax');", "model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');", "model.component('comp1').mesh('mesh1').run;", "model.component('comp1').cpl.create('maxop1', 'Maximum');", "model.component('comp1').cpl('maxop1').selection.all;",
        "model.study.create('std1');", "model.study('std1').create('stat', 'Stationary');", "model.study('std1').feature('stat').activate('solid', true);", "model.study('std1').createAutoSequences('all');", "model.study('std1').run;", *output_lines, "end", ""
    ])


def _build_two_dimensional_thermal_stress_script(cfg: dict[str, Any]) -> str:
    g, m, bc, mesh = cfg["geometry"]["parameters"], cfg["materials"], cfg["boundary_conditions"], cfg["mesh"]
    p = lambda name, spec: _param_line(name, spec, name)
    output_lines = [f"model.result.numerical.create('{tag}', 'EvalGlobal'); model.result.numerical('{tag}').set('expr', '{expr}');" for tag, expr in cfg["outputs"].items()]
    return "\n".join([
        f"function model = generated_build_{cfg['model_name']}()", "import com.comsol.model.*", "import com.comsol.model.util.*", "model = ModelUtil.create('Model');",
        p("L", g["L"]), p("W", g["W"]), p("E_mod", m["E"]), p("nu_mat", m["nu"]), p("rho_mat", m["rho"]), p("k_mat", m["k"]), p("Cp_mat", m["Cp"]), p("alpha_mat", m["alpha"]), p("T_hot", bc["T_hot"]), p("T_cold", bc["T_cold"]), p("hmax", mesh["hmax"]),
        "model.component.create('comp1', true);", "model.component('comp1').geom.create('geom1', 2);", "model.component('comp1').geom('geom1').create('r1', 'Rectangle');", "model.component('comp1').geom('geom1').feature('r1').set('size', {'L' 'W'});", "model.component('comp1').geom('geom1').run;",
        "model.component('comp1').material.create('mat1', 'Common');", "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho_mat');", "model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', 'k_mat');", "model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp_mat');", "model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', 'E_mod');", "model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', 'nu_mat');", "model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', 'alpha_mat');",
        "model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');", "model.component('comp1').physics('ht').selection.all;", "model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 1);", "model.component('comp1').physics('ht').feature('temp1').selection.set([1]);", "model.component('comp1').physics('ht').feature('temp1').set('T0', 'T_hot');", "model.component('comp1').physics('ht').create('temp2', 'TemperatureBoundary', 1);", "model.component('comp1').physics('ht').feature('temp2').selection.set([3]);", "model.component('comp1').physics('ht').feature('temp2').set('T0', 'T_cold');",
        "model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');", "model.component('comp1').physics('solid').selection.all;", "model.component('comp1').physics('solid').create('fix1', 'Fixed', 1);", "model.component('comp1').physics('solid').feature('fix1').selection.set([1]);", "model.component('comp1').multiphysics.create('te1', 'ThermalExpansion', 2);", "model.component('comp1').multiphysics('te1').selection.all;",
        "model.component('comp1').mesh.create('mesh1');", "model.component('comp1').mesh('mesh1').create('size1', 'Size');", "model.component('comp1').mesh('mesh1').feature('size1').set('custom', true);", "model.component('comp1').mesh('mesh1').feature('size1').set('hmax', 'hmax');", "model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');", "model.component('comp1').mesh('mesh1').run;", "model.component('comp1').cpl.create('maxop1', 'Maximum');", "model.component('comp1').cpl('maxop1').selection.all;", "model.study.create('std1');", "model.study('std1').create('stat', 'Stationary');", "model.study('std1').feature('stat').activate('ht', true);", "model.study('std1').feature('stat').activate('solid', true);", "model.study('std1').createAutoSequences('all');", "model.study('std1').run;", *output_lines, "end", ""
    ])
