from __future__ import annotations

from pathlib import Path
from typing import Any

from .constraints import format_value, load_constraints


def build_livelink_script(constraints_path: str | Path) -> str:
    cfg = load_constraints(constraints_path)
    return build_livelink_script_from_constraints(cfg)


def build_livelink_script_from_constraints(cfg: dict[str, Any]) -> str:
    model_name = cfg["model_name"]
    geometry = cfg["geometry"]["parameters"]
    materials = cfg["materials"]
    bc = cfg["boundary_conditions"]
    mesh = cfg["mesh"]
    outputs = cfg["outputs"]

    output_lines = []
    for tag, expr in outputs.items():
        output_lines.extend(
            [
                f"model.result.numerical.create('{tag}', 'EvalGlobal');",
                f"model.result.numerical('{tag}').set('expr', '{expr}');",
            ]
        )

    sweep_lines = []
    for name, values in cfg.get("sweep", {}).items():
        joined = " ".join(str(v) for v in values)
        sweep_lines.append(f"% Sweep candidate {name}: [{joined}]")

    return "\n".join(
        [
            f"function model = generated_build_{model_name}()",
            f"%GENERATED_BUILD_{model_name.upper()} Build a constrained COMSOL starter model.",
            "% Generated by comsol_training_small_model.",
            "%",
            "% Run inside COMSOL with MATLAB:",
            f"%   model = generated_build_{model_name};",
            "",
            "import com.comsol.model.*",
            "import com.comsol.model.util.*",
            "",
            "model = ModelUtil.create('Model');",
            f"model.label('{model_name}.mph');",
            "",
            _param_line("L", geometry["L"], "Rectangle length"),
            _param_line("W", geometry["W"], "Rectangle width"),
            _param_line("k", materials["k"], "Thermal conductivity"),
            _param_line("rho", materials["rho"], "Density"),
            _param_line("Cp", materials["Cp"], "Heat capacity"),
            _param_line("heat_flux", bc["heat_flux"], "Boundary heat flux"),
            _param_line("h", bc["h"], "Convective heat transfer coefficient"),
            _param_line("Text", bc["Text"], "External temperature"),
            _param_line("hmax", mesh["hmax"], "Maximum mesh size"),
            "",
            *sweep_lines,
            "",
            "model.component.create('comp1', true);",
            "model.component('comp1').geom.create('geom1', 2);",
            "model.component('comp1').geom('geom1').lengthUnit('m');",
            "model.component('comp1').geom('geom1').create('r1', 'Rectangle');",
            "model.component('comp1').geom('geom1').feature('r1').set('size', {'L' 'W'});",
            "model.component('comp1').geom('geom1').run;",
            "",
            "model.component('comp1').material.create('mat1', 'Common');",
            "model.component('comp1').material('mat1').label('Constrained solid');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', 'k');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho');",
            "model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp');",
            "",
            "model.component('comp1').physics.create('ht', 'HeatTransferInSolids', 'geom1');",
            "% Boundary selections are placeholders. Inspect geometry boundary numbers before production runs.",
            "model.component('comp1').physics('ht').create('hf1', 'HeatFluxBoundary', 1);",
            "model.component('comp1').physics('ht').feature('hf1').selection.set([1]);",
            "model.component('comp1').physics('ht').feature('hf1').set('q0', 'heat_flux');",
            "model.component('comp1').physics('ht').create('hf2', 'HeatFluxBoundary', 1);",
            "model.component('comp1').physics('ht').feature('hf2').selection.set([2 3 4]);",
            "model.component('comp1').physics('ht').feature('hf2').set('HeatFluxType', 'ConvectiveHeatFlux');",
            "model.component('comp1').physics('ht').feature('hf2').set('h', 'h');",
            "model.component('comp1').physics('ht').feature('hf2').set('Text', 'Text');",
            "",
            "model.component('comp1').mesh.create('mesh1');",
            "model.component('comp1').mesh('mesh1').create('size1', 'Size');",
            "model.component('comp1').mesh('mesh1').feature('size1').set('custom', true);",
            "model.component('comp1').mesh('mesh1').feature('size1').set('hmax', 'hmax');",
            "model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');",
            "model.component('comp1').mesh('mesh1').run;",
            "",
            "model.component('comp1').cpl.create('maxop1', 'Maximum');",
            "model.component('comp1').cpl('maxop1').selection.all;",
            "model.component('comp1').cpl.create('aveop1', 'Average');",
            "model.component('comp1').cpl('aveop1').selection.all;",
            "",
            "model.study.create('std1');",
            "model.study('std1').create('stat', 'Stationary');",
            "model.study('std1').createAutoSequences('all');",
            "model.study('std1').run;",
            "",
            *output_lines,
            "",
            "model.save(fullfile(pwd, [model.label]));",
            "end",
            "",
        ]
    )


def write_livelink_script(constraints_path: str | Path, output_path: str | Path) -> Path:
    destination = Path(output_path)
    destination.write_text(build_livelink_script(constraints_path), encoding="utf-8")
    return destination


def _param_line(name: str, spec: dict[str, Any], description: str) -> str:
    return f"model.param.set('{name}', '{format_value(spec)}', '{description}');"
